"""empty message

Revision ID: c966fb578969
Revises: 61b61c3fe1a1
Create Date: 2022-07-17 15:30:43.121497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c966fb578969'
down_revision = '61b61c3fe1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('owner', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'room', ['owner'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_column('room', 'owner')
    # ### end Alembic commands ###
